
title:
email: elif.meseci@hotmail.com
description: Elif's Blog
url: "elifmeseci.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: elifmeseci
twitter: "https://twitter.com/elifmeseci"
github_username:  elifmeseci
github: "https://github.com/elifmeseci"


# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
